### ISSUE TITLE
Bug: food can spawn inside the snake

### ISSUE THREAD

**Issue by TomJansen** [alirezaomidi/classic-snake-html5#1]
Thanks for this fun game :).
There is a small bug in which the food can spawn inside the snake, which can be confusing. Especially when the snake is very long.

**Comment by alirezaomidi** [comment]
Glad you enjoyed the game. You may want to fix the bug and create a pull request if you wish :)

**Comment by alirezaomidi** [comment]
Resolved and bugfixed in c42a806bd96ed11819b039aa8d7ee6e808e5310e.
